# Generated by Django 2.1.9 on 2025-01-24 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250124_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='receipient',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='p2ptransfer',
            name='transaction_ptr',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('RECIEVED', 'Recieved')], max_length=50),
        ),
        migrations.DeleteModel(
            name='P2PTransfer',
        ),
    ]
